[package]
name = "safari"
version = "2.3.6"
authors = ["Alex Chan <alex@alexwlchan.net>"]

[dependencies]
dirs = "2.0.2"
docopt = "0.8"
plist = "0.2.2"
reqwest = "0.9.24"
serde = "1.0.8"
serde_derive = "1.0"
tera = "0.10.6"
urlencoding = "1.0.0"
urlparse = "0.7.3"
